[package]
name = "opencensus"
version = "0.1.0"
authors = ["Glen Holcomb <MentalLabor@gmail.com>"]

[dependencies]
uuid = { version = "0.7.1", features = ["v4"] }
rand = "0.6.0"
fixedbitset = "0.1.9"
